### PR TITLE
feat: add unit tests

### PR DESCRIPTION
**Pull request by Ikem14**
**Add Unit Tests For QuizzesController**

This PR adds 3 unit tests for the QuizzesController:

- test_add_quiz
- test_add_quiz_date
- test_load_data

### CODE REVIEW

**Review by elee1220 — APPROVED** [review]
Looks good!

**Review by jayeshpamnani99 — APPROVED** [review]
LGTM!

**Comment by ajay47k** [comment]
Approved looks good.

**Review by ajay47k — APPROVED** [review]
Look's GOod.

**Review by wdzialakUMD — APPROVED** [review]
The unit tests look good and so does the json file added.

**Pull request merged**
